include_recipe 'validate_project_data'
include_recipe 'everything_rails::user'
include_recipe 'locale::default'
# include_recipe 'everything_rails::locale'
# include_recipe 'everything_rails::ssh'
include_recipe 'everything_rails::timezone'
include_recipe 'everything_rails::env_variables'
include_recipe 'everything_rails::apt'
include_recipe 'everything_rails::tree'
include_recipe 'everything_rails::git'
include_recipe 'everything_rails::git_setup'
include_recipe 'everything_rails::apache'
include_recipe 'everything_rails::nginx'
include_recipe 'everything_rails::nginx_host'
# include_recipe 'everything_rails::certbot'
include_recipe 'everything_rails::posgresql'
include_recipe 'everything_rails::ruby'
include_recipe 'everything_rails::image_magick'
include_recipe 'everything_rails::bundler'
# include_recipe 'everything_rails::rails'
# include_recipe 'everything_rails::capistrano'
include_recipe 'everything_rails::rmagick'
include_recipe 'everything_rails::puma'
include_recipe 'everything_rails::pg'
# include_recipe 'everything_rails::foreman'
include_recipe 'everything_rails::nodejs'
include_recipe 'everything_rails::yarn'
include_recipe 'everything_rails::redis'
include_recipe 'everything_rails::sidekiq'
